### ISSUE TITLE
Decks that combine 2 archetype in one deck

### ISSUE THREAD

**Issue by Roofne** [Badaro/MTGOArchetypeParser#7]
Some decks uses value or combo packages in a deck of another archetype
(exemple : https://mtgdecks.net/Pauper/boros-gates-decklist-by-simonxper-1414730)
That create conflicts where it should be counted in the 2 or more unique archetype

**Comment by Badaro** [comment]
As mentioned in the other issue, I don't speak french. :) From what I undestand of Google Translate you're talking about the problems where a specific deck sometimes includes a combo from another deck as a "value pack" and this causes a conflict, correct?

My usual approach in these cases is use a "DoesNotContain" clause to force the deck to go into one of the two conflicting archetypes. It's not the cleanest solution, but tends to work decently. But if you have a different proposal on how to solve this I'm willing to listen. 

One thing I've been prototyping is a way to automatically "decide" between conflicting decks, but I'm not sure which is the best rule to use for this decision. :D My first prototype is "in case of conflict, use the 'simpler' archetype, the one with less rules inside it", but I'm not sure this is the best way to go.

**Comment by Roofne** [comment]
(sry i think u were french)

One idea i have for this case is to use a list instead of a unique string for detected archetype.
With a tag system we can identify which macroarchetype (agro/control/combo), colors or package is used in a format.

**Comment by Badaro** [comment]
I have considered a "tagging" system, but that's essentially a full rewrite, not something I have time to do right now. I also considered having a tagging system in addition to the existing detection, so you could say "Dredge with Reanimator Package".

But this is going to require some time to prototype, test, and see if the results look better. So won't be done until I get some vacations from work. :D

**Comment by Badaro** [comment]
Not enough time or motivation to think of a tagging system, and an automated conflict resolution system was already implemented.
